spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/clinicajesus_db
    username: root
    password: mysql123

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka